---
name: Python Tests

on: [push]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2 
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install tox
      - name: Validate formatting
        run: tox -e format

  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.11"] 
        tox_env:
          - py311-dj41-wt41
          - py311-dj41-wt50
          - py311-dj41-wt51
          - py311-dj41-wt52
          - py311-dj41-wt60
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2 
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Test with tox
        run: tox -e ${{ matrix.tox_env }} -- index-url=https://pypi.python.org/simple/
      - name: Prepare artifacts
        run: mkdir -p .coverage-data && mv .coverage.* .coverage-data/
      - uses: actions/upload-artifact@v3 #
        with:
          name: coverage-data
          path: .coverage-data/

  coverage:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3 
        with:
          name: coverage-data
          path: .
      - name: Set up Python 3.8
        uses: actions/setup-python@v2 
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Prepare Coverage report
        run: tox -e coverage-report
      - name: Upload to codecov
        uses: codecov/codecov-action@v2